#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Contiene las constantes utilizadas por los archivos de actual modulo

# CONSTANTS
# Autor: PABLO PIZARRO @ ppizarro ~
# Fecha: JUNIO 2015

AMBIENT_COLOR_GREEN = [0.0, 0.403, 0.0]
AMBIENT_COLOR_PURPLE = [0.203, 0.0, 0.203]
AMBIENT_COLOR_RED = [0.403, 0.0, 0.0, 1.0]
AMBIENT_COLOR_YELLOW = [0.603, 0.603, 0.0]
AXES_LENGTH = 700
CAMERA_PHI = 45
CAMERA_RAD = 1700.0
CAMERA_ROT_VEL = 2.5
CAMERA_THETA = 56
COLOR_MAX = 5
COLOR_START = 0
DIFFUSE_COLOR_GREEN = [0.0, 0.505, 0.0]
DIFFUSE_COLOR_PURPLE = [0.301, 0.0, 0.301]
DIFFUSE_COLOR_RED = [0.556, 0.0, 0.0, 1.0]
DIFFUSE_COLOR_YELLOW = [0.803, 0.803, 0.0]
FPS = 60
LIGHT_ORBITAL_ANG_VEL = 1.0
LIGHT_ORBITAL_DESPLY_DELTA = 10
LIGHT_SUN_ANG_VEL = 1.0
LIGHT_SUN_SIZE = [15, 15, 15]
MATERIAL_START = 'material_silver'
MODEL_POSITION = [0, 0, 0]
MODEL_START = 0
MODELS = 16
NUM_LIGHTS = 2
OPERATOR_ADD = 0x0f60
OPERATOR_AND = 0x0f61
OPERATOR_DIFF = 0x0f62
OPERATOR_DIV = 0x0f63
OPERATOR_MOD = 0x0f64
OPERATOR_MULT = 0x0f65
OPERATOR_OR = 0x0f66
OPERATOR_POW = 0x0f67
OPERATOR_XOR = 0x0f68
PARALLAX = 0.02
PATH_IMAGES = "resources/images/"
PATH_MESHES = "resources/meshes/"
PATH_SHADERS = "resources/shaders/"
PROPERTIE_COLOR = "color"
PROPERTIE_MATERIAL_NAMES = 'material_names'
PROPERTIE_MATERIAL_SELECTED = 'material_selected'
PROPERTIE_MATERIAL_TOTAL = 'material_total'
PROPERTIE_MODEL = 'model'
PROPERTIE_MODEL_LIGHT = 'model_light'
PROPERTIE_MODEL_NAMES = 'model_names'
PROPERTIE_MODEL_PARALLAX = 'model_parallax'
PROPERTIE_MODEL_SELECTED = 'model_selected'
PROPERTIE_MODEL_TEXTURES = 'model_textures'
PROPERTIE_MODEL_TOTALS = 'model_total'
PROPERTIE_MODEL_TYPES = 'model_types'
PROPERTIE_TOTAL_COLORS = "total_colors"
SHOW_AXIS = True
SPECULAR_COLOR_GREEN = [0.0, 0.705, 0.0]
SPECULAR_COLOR_PURPLE = [0.505, 0.0, 0.505]
SPECULAR_COLOR_RED = [0.858, 0.0, 0.0, 1.0]
SPECULAR_COLOR_YELLOW = [0.901, 0.901, 0.0]
TEXTURE_BRICK = PATH_IMAGES + "brickwork-texture.jpg"
TEXTURE_BRICK_BUMP = PATH_IMAGES + "brickwork-bump.jpg"
TEXTURE_BRICK_NORMAL = PATH_IMAGES + "brickwork-normal.jpg"
TEXTURE_DOTS = PATH_IMAGES + "dots-texture.jpg"
TEXTURE_DOTS2 = PATH_IMAGES + "dots2-texture.jpg"
TEXTURE_DOTS2_BUMP = PATH_IMAGES + "dots2-bump.jpg"
TEXTURE_DOTS2_NORMAL = PATH_IMAGES + "dots2-normal.jpg"
TEXTURE_DOTS_BUMP = PATH_IMAGES + "dots-bump.jpg"
TEXTURE_DOTS_NORMAL = PATH_IMAGES + "dots-normal.jpg"
TEXTURE_METAL = PATH_IMAGES + "metal-texture.jpg"
TEXTURE_METAL_BUMP = PATH_IMAGES + "metal-bump.jpg"
TEXTURE_METAL_NORMAL = PATH_IMAGES + "metal-normal.jpg"
TEXTURE_WATER = PATH_IMAGES + "water-texture.jpg"
TEXTURE_WATER_BUMP = PATH_IMAGES + "water-bump.jpg"
TEXTURE_WATER_NORMAL = PATH_IMAGES + "water-normal.jpg"
WINDOWS_SIZE = 800, 600
